/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter.modules.sql;

import converter.modules.View;

/**
 *
 * @author Christopher
 */
public class SqlView extends View
{

    /** Creates new form View */
    public SqlView()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        sqlMode = new javax.swing.ButtonGroup();
        useSQLCheck = new javax.swing.JCheckBox();
        sqlSaveBtn = new javax.swing.JButton();
        dbTableNameTxt = new javax.swing.JTextField();
        dbTableNameLabel = new javax.swing.JLabel();
        dbNameTxt = new javax.swing.JTextField();
        dbNameLabel = new javax.swing.JLabel();
        dbUserLabel = new javax.swing.JLabel();
        dbUserTxt = new javax.swing.JTextField();
        dbPwLabel = new javax.swing.JLabel();
        dbPwTxt = new javax.swing.JPasswordField();
        dbPortTxt = new javax.swing.JTextField();
        dbPortLabel = new javax.swing.JLabel();
        dbHostTxt = new javax.swing.JTextField();
        dbHostLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sqlModeLabel = new javax.swing.JLabel();
        sqlModeReadRBtn = new javax.swing.JRadioButton();
        sqlModeWriteRBtn = new javax.swing.JRadioButton();
        sqlModeDelWriteRBtn = new javax.swing.JRadioButton();

        useSQLCheck.setText("SQL benutzen");
        useSQLCheck.setToolTipText("Soll die SQL-Unterstützung aktiviert werden?");
        useSQLCheck.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                useSQLCheckStateChanged(evt);
            }
        });

        sqlSaveBtn.setText("speichern");
        sqlSaveBtn.setToolTipText("Speichert die SQL Einstellungen");
        sqlSaveBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sqlSaveBtnActionPerformed(evt);
            }
        });

        dbTableNameTxt.setToolTipText("Tabellen Name z.B. \"Vertretungen\"");

        dbTableNameLabel.setText("Tabellenname:");

        dbNameTxt.setToolTipText("Datenbank Name z.B. \"Schuldatenbank\"");

        dbNameLabel.setText("Datenbankname:");

        dbUserLabel.setText("Benutzername:");

        dbUserTxt.setToolTipText("Benutzername z.B. \"admin\"");

        dbPwLabel.setText("Passwort:");

        dbPwTxt.setToolTipText("Passwort z.B. \"passw\"");

        dbPortTxt.setToolTipText("Datenbank Port; Standard:\"3306\"");

        dbPortLabel.setText("Port:");

        dbHostTxt.setToolTipText("Datenbank Host z.B. \"www.antonianum.de\"");

        dbHostLabel.setText("Datenbank Host:");

        sqlModeLabel.setText("Sql-Modus:");

        sqlModeReadRBtn.setText("lesen");
        sqlModeReadRBtn.setToolTipText("Aus der angegebenen Datenbank lesen, überschreibt HTML-Auslesen");

        sqlModeWriteRBtn.setText("anhängen");
        sqlModeWriteRBtn.setToolTipText("Die Vertretungen an die Datenbank anhängen");

        sqlModeDelWriteRBtn.setText("leeren und schreiben");
        sqlModeDelWriteRBtn.setToolTipText("Die Datenbank leeren und danach neu füllen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sqlSaveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dbNameLabel)
                            .addComponent(dbUserLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dbHostTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dbPortLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dbPortTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dbUserTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(dbNameTxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dbTableNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dbPwLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dbTableNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(dbPwTxt)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(useSQLCheck)
                            .addComponent(dbHostLabel)
                            .addComponent(sqlModeLabel))
                        .addGap(0, 287, Short.MAX_VALUE))
                    .addComponent(sqlModeReadRBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sqlModeWriteRBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sqlModeDelWriteRBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(useSQLCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbHostLabel)
                    .addComponent(dbHostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbPortLabel)
                    .addComponent(dbPortTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbNameLabel)
                    .addComponent(dbNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbTableNameLabel)
                    .addComponent(dbTableNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbUserTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbUserLabel)
                    .addComponent(dbPwLabel)
                    .addComponent(dbPwTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sqlModeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sqlModeReadRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sqlModeWriteRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sqlModeDelWriteRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(sqlSaveBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void useSQLCheckStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_useSQLCheckStateChanged
    {//GEN-HEADEREND:event_useSQLCheckStateChanged
        //Application.addToQueue("useSQLCheckStateChanged");
    }//GEN-LAST:event_useSQLCheckStateChanged

    private void sqlSaveBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sqlSaveBtnActionPerformed
    {//GEN-HEADEREND:event_sqlSaveBtnActionPerformed
        //Application.addToQueue("SQLsaveBtnActionPerformed");
    }//GEN-LAST:event_sqlSaveBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JLabel dbHostLabel;
    protected static javax.swing.JTextField dbHostTxt;
    protected static javax.swing.JLabel dbNameLabel;
    protected static javax.swing.JTextField dbNameTxt;
    protected static javax.swing.JLabel dbPortLabel;
    protected static javax.swing.JTextField dbPortTxt;
    protected static javax.swing.JLabel dbPwLabel;
    protected static javax.swing.JPasswordField dbPwTxt;
    protected static javax.swing.JLabel dbTableNameLabel;
    protected static javax.swing.JTextField dbTableNameTxt;
    protected static javax.swing.JLabel dbUserLabel;
    protected static javax.swing.JTextField dbUserTxt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.ButtonGroup sqlMode;
    protected static javax.swing.JRadioButton sqlModeDelWriteRBtn;
    protected static javax.swing.JLabel sqlModeLabel;
    protected static javax.swing.JRadioButton sqlModeReadRBtn;
    protected static javax.swing.JRadioButton sqlModeWriteRBtn;
    private javax.swing.JButton sqlSaveBtn;
    protected static javax.swing.JCheckBox useSQLCheck;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTabTitle()
    {
        return "SQL";
    }
}
