package eu.convertron.core.tabs;

import eu.convertron.applib.gui.LogPanel;
import eu.convertron.core.Resources;
import eu.convertron.interlib.interfaces.View;

@SuppressWarnings("serial")
public class OverviewView extends View
{
    /** Creates new form View */
    public OverviewView()
    {
        invokeAndWait(()
                ->
                {
                    logPanel = new LogPanel();
                    initComponents();
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        statusLabel = new javax.swing.JLabel();
        importLessonsButton = new javax.swing.JButton();
        generateAllButton = new javax.swing.JButton();
        exportLessonsButton = new javax.swing.JButton();
        createBackupButton = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        separator5 = new javax.swing.JSeparator();
        motdScrollPane = new javax.swing.JScrollPane();
        motdTextField = new javax.swing.JTextField();
        showDevInfosCheckBox = new javax.swing.JCheckBox();
        saveMotdButton = new javax.swing.JButton();
        showInfosCheckBox = new javax.swing.JCheckBox();
        separator1 = new javax.swing.JSeparator();
        separator2 = new javax.swing.JSeparator();
        separator3 = new javax.swing.JSeparator();
        separator4 = new javax.swing.JSeparator();
        logScrollPane = new javax.swing.JScrollPane(logPanel);

        statusLabel.setText("Status:");

        importLessonsButton.setText("Vertretungsplan importieren");
        importLessonsButton.setToolTipText("Importiert den Plan mithilfe des gewählten Import-Modules");

        generateAllButton.setText("Alles Generieren");
        generateAllButton.setToolTipText("Generiert den kompletten Plan");
        generateAllButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        exportLessonsButton.setText("Vertretungplan exportieren");
        exportLessonsButton.setToolTipText("Exportiert den Plan mithilfe der aktivierten Export-Module");

        createBackupButton.setText("Backup erstellen");
        createBackupButton.setToolTipText("Erstellt ein Backup des aktuellen Plans");

        logoLabel.setIcon(new javax.swing.ImageIcon(Resources.get("antonianumLogo.jpg")));
        logoLabel.setToolTipText("Antonianum Logo");

        separator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        motdScrollPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        motdScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        motdScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        motdScrollPane.setAutoscrolls(true);
        motdScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        motdTextField.setText("Laufschrift");
        motdTextField.setToolTipText("Text, der als Laufschrift angezeigt werden soll z.B. \"Dies ist eine Laufschrift\"");
        motdTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        motdTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        motdScrollPane.setViewportView(motdTextField);

        showDevInfosCheckBox.setText("Zeige Entwickler-Informationen im Status");
        showDevInfosCheckBox.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                showDevInfosCheckBoxItemStateChanged(evt);
            }
        });

        saveMotdButton.setText("Laufschrift speichern");

        showInfosCheckBox.setText("Zeige Informationen im Status");
        showInfosCheckBox.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                showInfosCheckBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveMotdButton, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(motdScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(exportLessonsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(separator4, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(separator2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(generateAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createBackupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(importLessonsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(separator3, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(separator1)
                    .addComponent(showDevInfosCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showInfosCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(separator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logScrollPane)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(separator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(generateAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(separator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(importLessonsButton)
                        .addGap(10, 10, 10)
                        .addComponent(exportLessonsButton)
                        .addGap(10, 10, 10)
                        .addComponent(createBackupButton)
                        .addGap(10, 10, 10)
                        .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(saveMotdButton)
                        .addGap(10, 10, 10)
                        .addComponent(motdScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(showInfosCheckBox)
                        .addGap(10, 10, 10)
                        .addComponent(showDevInfosCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logScrollPane)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showInfosCheckBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_showInfosCheckBoxItemStateChanged
    {//GEN-HEADEREND:event_showInfosCheckBoxItemStateChanged
        logPanel.setLogInfos(showInfosCheckBox.isSelected());
    }//GEN-LAST:event_showInfosCheckBoxItemStateChanged

    private void showDevInfosCheckBoxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_showDevInfosCheckBoxItemStateChanged
    {//GEN-HEADEREND:event_showDevInfosCheckBoxItemStateChanged
        logPanel.setLogDevInfos(showDevInfosCheckBox.isSelected());
    }//GEN-LAST:event_showDevInfosCheckBoxItemStateChanged

    public void addGenAllListener(Runnable task)
    {
        generateAllButton.addActionListener(getActionListenerToRunnable(task));
    }

    public void addImportListener(Runnable task)
    {
        importLessonsButton.addActionListener(getActionListenerToRunnable(task));
    }

    public void addExportListener(Runnable task)
    {
        exportLessonsButton.addActionListener(getActionListenerToRunnable(task));
    }

    public void addBackupListener(Runnable task)
    {
        createBackupButton.addActionListener(getActionListenerToRunnable(task));
    }

    public void addSaveMotdListener(Runnable task)
    {
        saveMotdButton.addActionListener(getActionListenerToRunnable(task));
    }

    public void setMotdText(String motd)
    {
        invokeLater(() -> motdTextField.setText(motd));
    }

    public String getMotdText()
    {
        return motdTextField.getText();
    }

    @Override
    public String getTabTitle()
    {
        return "Übersicht";
    }

    private LogPanel logPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBackupButton;
    private javax.swing.JButton exportLessonsButton;
    private javax.swing.JButton generateAllButton;
    private javax.swing.JButton importLessonsButton;
    private javax.swing.JScrollPane logScrollPane;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JScrollPane motdScrollPane;
    private javax.swing.JTextField motdTextField;
    private javax.swing.JButton saveMotdButton;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JSeparator separator3;
    private javax.swing.JSeparator separator4;
    private javax.swing.JSeparator separator5;
    private javax.swing.JCheckBox showDevInfosCheckBox;
    private javax.swing.JCheckBox showInfosCheckBox;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
