package convertron.tabs.modules;

import interlib.interfaces.View;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;

public class ModuleView extends View
{
    private static final long serialVersionUID = 1L;

    /** Creates new form ModuleView */
    public ModuleView()
    {
        initComponents();

        availableOutputModulesListModel = new DefaultListModel<>();
        activeOutputModulesListModel = new DefaultListModel<>();
        activeInputModuleComboModel = new DefaultComboBoxModel<>();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        fileChooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableOutputModulesList = new javax.swing.JList<ModuleHolder>(availableOutputModulesListModel);
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        activeOutputModulesList = new javax.swing.JList<ModuleHolder>(activeOutputModulesListModel);
        activateBtn = new javax.swing.JButton();
        deactivateBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        activeInputModuleCombo = new javax.swing.JComboBox<ModuleHolder>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        saveBtn = new javax.swing.JButton();
        manageModulesBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(642, 201));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jScrollPane1.setViewportView(availableOutputModulesList);

        jLabel1.setText("Verfügbare Output Module");

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jScrollPane2.setViewportView(activeOutputModulesList);

        activateBtn.setText("->");
        activateBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                activateBtnActionPerformed(evt);
            }
        });

        deactivateBtn.setText("<-");
        deactivateBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deactivateBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Aktive Output Module");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setText("Aktives Input Modul");

        saveBtn.setText("speichern");
        saveBtn.setToolTipText("Speichert die Änderungen, damit sie nach einem Neustart erhalten bleiben");

        manageModulesBtn.setText("Module verwalten");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activateBtn)
                    .addComponent(deactivateBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(activeInputModuleCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageModulesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jSeparator3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(activeInputModuleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(manageModulesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(activateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deactivateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void activateBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_activateBtnActionPerformed
    {//GEN-HEADEREND:event_activateBtnActionPerformed
        List<ModuleHolder> affected = availableOutputModulesList.getSelectedValuesList();
        for(ModuleHolder m : affected)
        {
            activeOutputModulesListModel.addElement(m);
            availableOutputModulesListModel.removeElement(m);
        }
    }//GEN-LAST:event_activateBtnActionPerformed

    private void deactivateBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deactivateBtnActionPerformed
    {//GEN-HEADEREND:event_deactivateBtnActionPerformed
        List<ModuleHolder> affected = activeOutputModulesList.getSelectedValuesList();
        for(ModuleHolder m : affected)
        {
            availableOutputModulesListModel.addElement(m);
            activeOutputModulesListModel.removeElement(m);
        }
    }//GEN-LAST:event_deactivateBtnActionPerformed

    @Override
    public String getTabTitle()
    {
        return "Module";
    }

    // <editor-fold defaultstate="collapsed" desc="Getter">
    public DefaultListModel<ModuleHolder> getActiveOutputModulesListModel()
    {
        return activeOutputModulesListModel;
    }

    public DefaultListModel<ModuleHolder> getAvailableOutputModulesListModel()
    {
        return availableOutputModulesListModel;
    }

    public DefaultComboBoxModel<ModuleHolder> getActiveInputModuleComboModel()
    {
        return activeInputModuleComboModel;
    }

    public JButton getManageModulesBtn()
    {
        return manageModulesBtn;
    }

    public JButton getSaveBtn()
    {
        return saveBtn;
    }
    // </editor-fold>

    private javax.swing.DefaultListModel<ModuleHolder> activeOutputModulesListModel;
    private javax.swing.DefaultListModel<ModuleHolder> availableOutputModulesListModel;
    private javax.swing.DefaultComboBoxModel<ModuleHolder> activeInputModuleComboModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activateBtn;
    private javax.swing.JComboBox<ModuleHolder> activeInputModuleCombo;
    private javax.swing.JList<ModuleHolder> activeOutputModulesList;
    private javax.swing.JList<ModuleHolder> availableOutputModulesList;
    private javax.swing.JButton deactivateBtn;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton manageModulesBtn;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
