/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convertron.tabs.overview;

import interlib.interfaces.View;
import interlib.util.Logger;

/**
 *
 * @author Christopher
 */
public class OverviewView extends View
{
    private static final long serialVersionUID = 1L;

    /** Creates new form View */
    public OverviewView()
    {
        initComponents();
        Logger.setLogTextBox(log);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        importLessonsBtn = new javax.swing.JButton();
        genAllBtn = new javax.swing.JButton();
        exportLessonsBtn = new javax.swing.JButton();
        createBackupBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        motdTxt = new javax.swing.JTextField();
        showInfosCheck = new javax.swing.JCheckBox();
        saveMotdBtn = new javax.swing.JButton();

        log.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        log.setToolTipText("Zeigt den Status des Programms an");
        log.setFocusable(false);
        jScrollPane1.setViewportView(log);

        jLabel1.setText("Status:");

        importLessonsBtn.setText("Vertretungsplan importieren");
        importLessonsBtn.setToolTipText("Importiert den Plan mithilfe des gewählten Import-Modules");
        importLessonsBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                importLessonsBtnActionPerformed(evt);
            }
        });

        genAllBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genAllBtn.setText("<html><center>Alles<br>\ngenerieren</center></html>");
        genAllBtn.setToolTipText("Generiert den kompletten Plan");
        genAllBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        genAllBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                genAllBtnActionPerformed(evt);
            }
        });

        exportLessonsBtn.setText("Vertretungplan exportieren");
        exportLessonsBtn.setToolTipText("Exportiert den Plan mithilfe der aktivierten Export-Module");
        exportLessonsBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exportLessonsBtnActionPerformed(evt);
            }
        });

        createBackupBtn.setText("Backup erstellen");
        createBackupBtn.setToolTipText("Erstellt ein Backup des aktuellen Plans");
        createBackupBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                createBackupBtnActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/convertron/res/antonianumLogo.jpg"))); // NOI18N
        jLabel5.setToolTipText("Antonianum Logo");

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setAutoscrolls(true);
        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        motdTxt.setText("Laufschrift");
        motdTxt.setToolTipText("Text, der als Laufschrift angezeigt werden soll z.B. \"Dies ist eine Laufschrift\"");
        motdTxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        motdTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        motdTxt.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                motdTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                motdTxtFocusLost(evt);
            }
        });
        jScrollPane4.setViewportView(motdTxt);

        showInfosCheck.setSelected(true);
        showInfosCheck.setText("Zeige Informationen");
        showInfosCheck.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                showInfosCheckItemStateChanged(evt);
            }
        });

        saveMotdBtn.setText("Laufschrift speichern");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(genAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(importLessonsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(exportLessonsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createBackupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(saveMotdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(showInfosCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(importLessonsBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exportLessonsBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createBackupBtn))
                            .addComponent(genAllBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveMotdBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showInfosCheck))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void importLessonsBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_importLessonsBtnActionPerformed
    {//GEN-HEADEREND:event_importLessonsBtnActionPerformed
        //Application.addToQueue("genTodayBtnActionPerformed");
    }//GEN-LAST:event_importLessonsBtnActionPerformed

    private void genAllBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_genAllBtnActionPerformed
    {//GEN-HEADEREND:event_genAllBtnActionPerformed
        //Application.addToQueue("genAllBtnActionPerformed");
    }//GEN-LAST:event_genAllBtnActionPerformed

    private void exportLessonsBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exportLessonsBtnActionPerformed
    {//GEN-HEADEREND:event_exportLessonsBtnActionPerformed
        //Application.addToQueue("genMotdBtnActionPerformed");
    }//GEN-LAST:event_exportLessonsBtnActionPerformed

    private void createBackupBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_createBackupBtnActionPerformed
    {//GEN-HEADEREND:event_createBackupBtnActionPerformed
        //Application.addToQueue("createBackupBtnActionPerformed");
    }//GEN-LAST:event_createBackupBtnActionPerformed

    private void motdTxtFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_motdTxtFocusGained
    {//GEN-HEADEREND:event_motdTxtFocusGained
        //Application.addToQueue("motdTxtFocusGained");
    }//GEN-LAST:event_motdTxtFocusGained

    private void motdTxtFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_motdTxtFocusLost
    {//GEN-HEADEREND:event_motdTxtFocusLost
        //Application.addToQueue("motdTxtFocusLost");
    }//GEN-LAST:event_motdTxtFocusLost

    private void showInfosCheckItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_showInfosCheckItemStateChanged
    {//GEN-HEADEREND:event_showInfosCheckItemStateChanged
        Logger.setLogInfos(showInfosCheck.isSelected());
    }//GEN-LAST:event_showInfosCheckItemStateChanged

    public void setCurrentTaskMessage(String message)
    {

    }

    public void setCurrentState(boolean working)
    {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBackupBtn;
    private javax.swing.JButton exportLessonsBtn;
    private javax.swing.JButton genAllBtn;
    private javax.swing.JButton importLessonsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextPane log;
    private javax.swing.JTextField motdTxt;
    private javax.swing.JButton saveMotdBtn;
    private javax.swing.JCheckBox showInfosCheck;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTabTitle()
    {
        return "Übersicht";
    }
}
