package convertron.tabs.overview;

import convertron.settings.CoreSettings;
import convertron.tabs.settings.SettingHandler;
import convertron.tabs.settings.TextFieldHandler;
import interlib.interfaces.View;
import interlib.logging.LogRenderer;
import interlib.logging.LogTable;

@SuppressWarnings("serial")
public class OverviewView extends View
{
    /** Creates new form View */
    public OverviewView()
    {
        initComponents();
        initTable();
    }

    private void initTable()
    {
        statusTable.setModel(LogTable.getLogModel());
        statusTable.getColumnModel().getColumn(0).setMaxWidth(50);

        LogRenderer logRenderer = new LogRenderer();
        statusTable.getColumnModel().getColumn(0).setCellRenderer(logRenderer);
        statusTable.getColumnModel().getColumn(1).setCellRenderer(logRenderer);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        statusLabel = new javax.swing.JLabel();
        importLessonsButton = new javax.swing.JButton();
        generateAllButton = new javax.swing.JButton();
        exportLessonsButton = new javax.swing.JButton();
        createBackupButton = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        separator5 = new javax.swing.JSeparator();
        motdScrollPane = new javax.swing.JScrollPane();
        motdTextField = new javax.swing.JTextField();
        showDevInfosCheckBox = new javax.swing.JCheckBox();
        saveMotdButton = new javax.swing.JButton();
        showInfosCheckBox = new javax.swing.JCheckBox();
        statusScrollPane = new javax.swing.JScrollPane();
        statusTable = new javax.swing.JTable();
        separator1 = new javax.swing.JSeparator();
        separator2 = new javax.swing.JSeparator();
        separator3 = new javax.swing.JSeparator();
        separator4 = new javax.swing.JSeparator();

        statusLabel.setText("Status:");

        importLessonsButton.setText("Vertretungsplan importieren");
        importLessonsButton.setToolTipText("Importiert den Plan mithilfe des gewählten Import-Modules");

        generateAllButton.setText("Alles Generieren");
        generateAllButton.setToolTipText("Generiert den kompletten Plan");
        generateAllButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        exportLessonsButton.setText("Vertretungplan exportieren");
        exportLessonsButton.setToolTipText("Exportiert den Plan mithilfe der aktivierten Export-Module");

        createBackupButton.setText("Backup erstellen");
        createBackupButton.setToolTipText("Erstellt ein Backup des aktuellen Plans");

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/convertron/res/antonianumLogo.jpg"))); // NOI18N
        logoLabel.setToolTipText("Antonianum Logo");

        separator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        motdScrollPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        motdScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        motdScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        motdScrollPane.setAutoscrolls(true);
        motdScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        motdTextField.setText("Laufschrift");
        motdTextField.setToolTipText("Text, der als Laufschrift angezeigt werden soll z.B. \"Dies ist eine Laufschrift\"");
        motdTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        motdTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        motdScrollPane.setViewportView(motdTextField);

        showDevInfosCheckBox.setText("Zeige Entwickler-Informationen im Status");
        showDevInfosCheckBox.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                showDevInfosCheckBoxStateChanged(evt);
            }
        });

        saveMotdButton.setText("Laufschrift speichern");

        showInfosCheckBox.setText("Zeige Informationen im Status");
        showInfosCheckBox.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                showInfosCheckBoxStateChanged(evt);
            }
        });

        statusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        statusTable.setShowVerticalLines(false);
        statusTable.setTableHeader(null);
        statusScrollPane.setViewportView(statusTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveMotdButton, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(motdScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(exportLessonsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(separator4, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(separator2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(generateAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createBackupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(importLessonsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(separator3, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(separator1)
                    .addComponent(showDevInfosCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showInfosCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(separator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(statusScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(separator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(generateAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(separator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(importLessonsButton)
                        .addGap(10, 10, 10)
                        .addComponent(exportLessonsButton)
                        .addGap(10, 10, 10)
                        .addComponent(createBackupButton)
                        .addGap(10, 10, 10)
                        .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(saveMotdButton)
                        .addGap(10, 10, 10)
                        .addComponent(motdScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(showInfosCheckBox)
                        .addGap(10, 10, 10)
                        .addComponent(showDevInfosCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statusLabel)
                        .addGap(10, 10, 10)
                        .addComponent(statusScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showInfosCheckBoxStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_showInfosCheckBoxStateChanged
    {//GEN-HEADEREND:event_showInfosCheckBoxStateChanged
        LogTable.setLogInfos(showInfosCheckBox.isSelected());
    }//GEN-LAST:event_showInfosCheckBoxStateChanged

    private void showDevInfosCheckBoxStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_showDevInfosCheckBoxStateChanged
    {//GEN-HEADEREND:event_showDevInfosCheckBoxStateChanged
        LogTable.setLogDevInfos(showDevInfosCheckBox.isSelected());
    }//GEN-LAST:event_showDevInfosCheckBoxStateChanged

    public void addGenAllListener(Runnable task)
    {
        generateAllButton.addActionListener(getActionListenerToRunnable(task));
    }

    public void addImportListener(Runnable task)
    {
        importLessonsButton.addActionListener(getActionListenerToRunnable(task));
    }

    public void addExportListener(Runnable task)
    {
        exportLessonsButton.addActionListener(getActionListenerToRunnable(task));
    }

    public void addBackupListener(Runnable task)
    {
        createBackupButton.addActionListener(getActionListenerToRunnable(task));
    }

    public void addSaveMotdListener(Runnable task)
    {
        saveMotdButton.addActionListener(getActionListenerToRunnable(task));
    }

    public SettingHandler createMotdSettingHandler()
    {
        return new TextFieldHandler(motdTextField, CoreSettings.motdText);
    }

    @Override
    public String getTabTitle()
    {
        return "Übersicht";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBackupButton;
    private javax.swing.JButton exportLessonsButton;
    private javax.swing.JButton generateAllButton;
    private javax.swing.JButton importLessonsButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JScrollPane motdScrollPane;
    private javax.swing.JTextField motdTextField;
    private javax.swing.JButton saveMotdButton;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JSeparator separator3;
    private javax.swing.JSeparator separator4;
    private javax.swing.JSeparator separator5;
    private javax.swing.JCheckBox showDevInfosCheckBox;
    private javax.swing.JCheckBox showInfosCheckBox;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JScrollPane statusScrollPane;
    private javax.swing.JTable statusTable;
    // End of variables declaration//GEN-END:variables
}
