/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convertron.tabs.overview;

import convertron.core.CoreSettings;
import convertron.tabs.settings.SettingHandler;
import convertron.tabs.settings.TextFieldHandler;
import interlib.interfaces.View;
import interlib.logging.LogRenderer;
import interlib.logging.LogTable;

/**
 *
 * @author Christopher
 */
@SuppressWarnings("serial")
public class OverviewView extends View
{
    /** Creates new form View */
    public OverviewView()
    {
        initComponents();
        initTable();
    }

    private void initTable()
    {
        jTable1.setModel(LogTable.getLogModel());
        jTable1.getColumnModel().getColumn(0).setMaxWidth(50);

        LogRenderer logRenderer = new LogRenderer();
        jTable1.getColumnModel().getColumn(0).setCellRenderer(logRenderer);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(logRenderer);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        importLessonsBtn = new javax.swing.JButton();
        genAllBtn = new javax.swing.JButton();
        exportLessonsBtn = new javax.swing.JButton();
        createBackupBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        motdTxt = new javax.swing.JTextField();
        showDevInfosCheck = new javax.swing.JCheckBox();
        saveMotdBtn = new javax.swing.JButton();
        showInfosCheck = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setMinimumSize(new java.awt.Dimension(793, 493));
        setPreferredSize(new java.awt.Dimension(793, 493));

        jLabel1.setText("Status:");

        importLessonsBtn.setText("Vertretungsplan importieren");
        importLessonsBtn.setToolTipText("Importiert den Plan mithilfe des gewählten Import-Modules");

        genAllBtn.setText("Alles Generieren");
        genAllBtn.setToolTipText("Generiert den kompletten Plan");
        genAllBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        exportLessonsBtn.setText("Vertretungplan exportieren");
        exportLessonsBtn.setToolTipText("Exportiert den Plan mithilfe der aktivierten Export-Module");

        createBackupBtn.setText("Backup erstellen");
        createBackupBtn.setToolTipText("Erstellt ein Backup des aktuellen Plans");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/convertron/res/antonianumLogo.jpg"))); // NOI18N
        jLabel5.setToolTipText("Antonianum Logo");

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setAutoscrolls(true);
        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        motdTxt.setText("Laufschrift");
        motdTxt.setToolTipText("Text, der als Laufschrift angezeigt werden soll z.B. \"Dies ist eine Laufschrift\"");
        motdTxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        motdTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(motdTxt);

        showDevInfosCheck.setText("Zeige Entwickler-Informationen im Status");
        showDevInfosCheck.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                showDevInfosCheckStateChanged(evt);
            }
        });

        saveMotdBtn.setText("Laufschrift speichern");

        showInfosCheck.setText("Zeige Informationen im Status");
        showInfosCheck.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                showInfosCheckStateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jTable1.setShowVerticalLines(false);
        jTable1.setTableHeader(null);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveMotdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(exportLessonsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(genAllBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createBackupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(importLessonsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(showDevInfosCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showInfosCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(genAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(importLessonsBtn)
                        .addGap(10, 10, 10)
                        .addComponent(exportLessonsBtn)
                        .addGap(10, 10, 10)
                        .addComponent(createBackupBtn)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(saveMotdBtn)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(showInfosCheck)
                        .addGap(10, 10, 10)
                        .addComponent(showDevInfosCheck))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showInfosCheckStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_showInfosCheckStateChanged
    {//GEN-HEADEREND:event_showInfosCheckStateChanged
        LogTable.setLogInfos(showInfosCheck.isSelected());
    }//GEN-LAST:event_showInfosCheckStateChanged

    private void showDevInfosCheckStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_showDevInfosCheckStateChanged
    {//GEN-HEADEREND:event_showDevInfosCheckStateChanged
        LogTable.setLogDevInfos(showDevInfosCheck.isSelected());
    }//GEN-LAST:event_showDevInfosCheckStateChanged

    public void addGenAllListener(Runnable task)
    {
        genAllBtn.addActionListener(getActionListenerToRunnable(task));
    }

    public void addImportListener(Runnable task)
    {
        importLessonsBtn.addActionListener(getActionListenerToRunnable(task));
    }

    public void addExportListener(Runnable task)
    {
        exportLessonsBtn.addActionListener(getActionListenerToRunnable(task));
    }

    public void addBackupListener(Runnable task)
    {
        createBackupBtn.addActionListener(getActionListenerToRunnable(task));
    }

    public void addSaveMotdListener(Runnable task)
    {
        saveMotdBtn.addActionListener(getActionListenerToRunnable(task));
    }

    public SettingHandler createMotdSettingHandler()
    {
        return new TextFieldHandler(motdTxt, CoreSettings.motdText);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBackupBtn;
    private javax.swing.JButton exportLessonsBtn;
    private javax.swing.JButton genAllBtn;
    private javax.swing.JButton importLessonsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField motdTxt;
    private javax.swing.JButton saveMotdBtn;
    private javax.swing.JCheckBox showDevInfosCheck;
    private javax.swing.JCheckBox showInfosCheck;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTabTitle()
    {
        return "Übersicht";
    }
}
