/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter.modules.design;

import converter.modules.View;

/**
 *
 * @author Christopher
 */
public class DesignView extends View
{

    /** Creates new form View */
    public DesignView()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jColorChooser1 = new javax.swing.JColorChooser();
        bgPlanLabel = new javax.swing.JLabel();
        colorPlanCombo = new javax.swing.JComboBox<String>();
        colorPlanPanel = new javax.swing.JPanel();
        colorMotdPanel = new javax.swing.JPanel();
        deleteColor = new javax.swing.JButton();
        addColorBtn = new javax.swing.JButton();
        colorNameTxt = new javax.swing.JTextField();
        bgMotdLabel = new javax.swing.JLabel();
        colorMotdCombo = new javax.swing.JComboBox<String>();
        backgroundColorsLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        bgTableLabel = new javax.swing.JLabel();
        colorTableCombo = new javax.swing.JComboBox<String>();
        colorTablePanel = new javax.swing.JPanel();
        otherColorsLabel = new javax.swing.JLabel();
        otherBorderLabel = new javax.swing.JLabel();
        colorBorderCombo = new javax.swing.JComboBox<String>();
        colorBorderPanel = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        saveDesignBtn = new javax.swing.JButton();
        designTypeSubPanel = new javax.swing.JPanel();
        deleteTypeBtn = new javax.swing.JButton();
        addTypeBtn = new javax.swing.JButton();
        typeToEditTxt = new javax.swing.JTextField();
        typeToEditCombo = new javax.swing.JComboBox<String>();
        tteFontColorLabel = new javax.swing.JLabel();
        fontColorCombo = new javax.swing.JComboBox<String>();
        fontColorPanel = new javax.swing.JPanel();
        tteBgLabel = new javax.swing.JLabel();
        backgroundColorCombo = new javax.swing.JComboBox<String>();
        backgroundColorPanel = new javax.swing.JPanel();
        tteFontTypeLabel = new javax.swing.JLabel();
        fontTypeTxt = new javax.swing.JTextField();
        tteFontSizeLabel = new javax.swing.JLabel();
        fontSizeTxt = new javax.swing.JTextField();
        boldCheck = new javax.swing.JCheckBox();
        italicCheck = new javax.swing.JCheckBox();
        typeToEditLabel = new javax.swing.JLabel();

        bgPlanLabel.setText("Vertretungplan");

        colorPlanCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Keine Farbe" }));
        colorPlanCombo.setToolTipText("Hintergrundfarbe des Vertretungsplans");
        colorPlanCombo.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                colorPlanComboItemStateChanged(evt);
            }
        });

        colorPlanPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout colorPlanPanelLayout = new javax.swing.GroupLayout(colorPlanPanel);
        colorPlanPanel.setLayout(colorPlanPanelLayout);
        colorPlanPanelLayout.setHorizontalGroup(
            colorPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        colorPlanPanelLayout.setVerticalGroup(
            colorPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        colorMotdPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout colorMotdPanelLayout = new javax.swing.GroupLayout(colorMotdPanel);
        colorMotdPanel.setLayout(colorMotdPanelLayout);
        colorMotdPanelLayout.setHorizontalGroup(
            colorMotdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        colorMotdPanelLayout.setVerticalGroup(
            colorMotdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        deleteColor.setText("Farbe löschen");
        deleteColor.setToolTipText("Angegebene Farbe löschen");
        deleteColor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteColorActionPerformed(evt);
            }
        });

        addColorBtn.setText("Farbe bearbeiten/hinzufügen");
        addColorBtn.setToolTipText("Angegebene Farbe bearbeiten/hinzufügen");
        addColorBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addColorBtnActionPerformed(evt);
            }
        });

        colorNameTxt.setForeground(java.awt.Color.gray);
        colorNameTxt.setText("Farbenname");
        colorNameTxt.setToolTipText("Name der Farbe, die hinzugefügt/bearbeitet werden soll z.B. \"Antonsblau\"");
        colorNameTxt.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                colorNameTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                colorNameTxtFocusLost(evt);
            }
        });

        bgMotdLabel.setText("Laufschrift");

        colorMotdCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Keine Farbe" }));
        colorMotdCombo.setToolTipText("Hintergrundfarbe der Laufschrift");
        colorMotdCombo.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                colorMotdComboItemStateChanged(evt);
            }
        });

        backgroundColorsLabel.setText("Hintergrundfarben");

        bgTableLabel.setText("Tabelle");

        colorTableCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Keine Farbe" }));
        colorTableCombo.setToolTipText("Hintergrundfarbe der Tabelle");
        colorTableCombo.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                colorTableComboItemStateChanged(evt);
            }
        });

        colorTablePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout colorTablePanelLayout = new javax.swing.GroupLayout(colorTablePanel);
        colorTablePanel.setLayout(colorTablePanelLayout);
        colorTablePanelLayout.setHorizontalGroup(
            colorTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        colorTablePanelLayout.setVerticalGroup(
            colorTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        otherColorsLabel.setText("andere Farben");

        otherBorderLabel.setText("Rahmen");

        colorBorderCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Keine Farbe" }));
        colorBorderCombo.setToolTipText("Farbe des Rahmens, der um die Frames angezeigt wird");
        colorBorderCombo.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                colorBorderComboItemStateChanged(evt);
            }
        });

        colorBorderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout colorBorderPanelLayout = new javax.swing.GroupLayout(colorBorderPanel);
        colorBorderPanel.setLayout(colorBorderPanelLayout);
        colorBorderPanelLayout.setHorizontalGroup(
            colorBorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        colorBorderPanelLayout.setVerticalGroup(
            colorBorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        saveDesignBtn.setText("Style anwenden");
        saveDesignBtn.setToolTipText("Den, oben eingestellten, Style für den Plan anwenden");
        saveDesignBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveDesignBtnActionPerformed(evt);
            }
        });

        deleteTypeBtn.setText("löschen");
        deleteTypeBtn.setToolTipText("Eine Vertretungsart löschen");
        deleteTypeBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteTypeBtnActionPerformed(evt);
            }
        });

        addTypeBtn.setText("hinzufügen");
        addTypeBtn.setToolTipText("Eine neue, zu differenzierende, Vertretungsart erstellen");
        addTypeBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addTypeBtnActionPerformed(evt);
            }
        });

        typeToEditTxt.setForeground(java.awt.Color.gray);
        typeToEditTxt.setText("Vertretungsart");
        typeToEditTxt.setToolTipText("Name einer neuen, zu differenzierenden, Vertretungsart z.B. \"Raum-Vtr.\"");
        typeToEditTxt.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                typeToEditTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                typeToEditTxtFocusLost(evt);
            }
        });

        typeToEditCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Überschrift", "Stufenname", "Laufschrift", "Tabelle" }));
        typeToEditCombo.setToolTipText("Bereich des Designs der bearbeitet werden soll");
        typeToEditCombo.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                typeToEditComboItemStateChanged(evt);
            }
        });

        tteFontColorLabel.setText("Schriftfarbe");

        fontColorCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Keine Farbe" }));
        fontColorCombo.setToolTipText("Schriftfarbe für den gewählten Bereich festlegen");
        fontColorCombo.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                fontColorComboItemStateChanged(evt);
            }
        });

        fontColorPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout fontColorPanelLayout = new javax.swing.GroupLayout(fontColorPanel);
        fontColorPanel.setLayout(fontColorPanelLayout);
        fontColorPanelLayout.setHorizontalGroup(
            fontColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        fontColorPanelLayout.setVerticalGroup(
            fontColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        tteBgLabel.setText("Hintergrundfarbe");

        backgroundColorCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Keine Farbe" }));
        backgroundColorCombo.setToolTipText("Hintergrundfarbe für den gewählten Bereich festlegen");
        backgroundColorCombo.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                backgroundColorComboItemStateChanged(evt);
            }
        });

        backgroundColorPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout backgroundColorPanelLayout = new javax.swing.GroupLayout(backgroundColorPanel);
        backgroundColorPanel.setLayout(backgroundColorPanelLayout);
        backgroundColorPanelLayout.setHorizontalGroup(
            backgroundColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        backgroundColorPanelLayout.setVerticalGroup(
            backgroundColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        tteFontTypeLabel.setText("Schriftart");

        fontTypeTxt.setToolTipText("Schriftart für den gewählten Bereich festlegen z.B. \"calibri\"");
        fontTypeTxt.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                fontTypeTxtMouseExited(evt);
            }
        });

        tteFontSizeLabel.setText("Schriftgröße");

        fontSizeTxt.setToolTipText("Schriftgröße für den gewählten Bereich festlegen z.B. \"12\"");
        fontSizeTxt.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                fontSizeTxtMouseExited(evt);
            }
        });

        boldCheck.setText("Fett");
        boldCheck.setToolTipText("Soll die Schrift des gewählten Bereichs fett gedruckt werden?");
        boldCheck.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                boldCheckActionPerformed(evt);
            }
        });

        italicCheck.setText("Kursiv");
        italicCheck.setToolTipText("Soll die Schrift des gewählten Bereichs kursiv gedruckt werden?");
        italicCheck.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                italicCheckActionPerformed(evt);
            }
        });

        typeToEditLabel.setText("Text");

        javax.swing.GroupLayout designTypeSubPanelLayout = new javax.swing.GroupLayout(designTypeSubPanel);
        designTypeSubPanel.setLayout(designTypeSubPanelLayout);
        designTypeSubPanelLayout.setHorizontalGroup(
            designTypeSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(designTypeSubPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(designTypeSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(designTypeSubPanelLayout.createSequentialGroup()
                        .addComponent(tteFontTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fontTypeTxt))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, designTypeSubPanelLayout.createSequentialGroup()
                        .addGroup(designTypeSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tteFontColorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(typeToEditLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(designTypeSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(typeToEditCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, designTypeSubPanelLayout.createSequentialGroup()
                                .addComponent(fontColorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fontColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(designTypeSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(designTypeSubPanelLayout.createSequentialGroup()
                        .addComponent(typeToEditTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(designTypeSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(designTypeSubPanelLayout.createSequentialGroup()
                                .addComponent(addTypeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteTypeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(designTypeSubPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(designTypeSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(designTypeSubPanelLayout.createSequentialGroup()
                                        .addComponent(boldCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(italicCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(designTypeSubPanelLayout.createSequentialGroup()
                                        .addComponent(backgroundColorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(backgroundColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(designTypeSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, designTypeSubPanelLayout.createSequentialGroup()
                            .addComponent(tteFontSizeLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fontSizeTxt))
                        .addComponent(tteBgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        designTypeSubPanelLayout.setVerticalGroup(
            designTypeSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(designTypeSubPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(designTypeSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeToEditCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeToEditTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTypeBtn)
                    .addComponent(deleteTypeBtn)
                    .addComponent(typeToEditLabel))
                .addGap(18, 18, 18)
                .addGroup(designTypeSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, designTypeSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tteFontColorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fontColorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(designTypeSubPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fontColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(designTypeSubPanelLayout.createSequentialGroup()
                        .addGroup(designTypeSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backgroundColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(designTypeSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tteBgLabel)
                                .addComponent(backgroundColorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(designTypeSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tteFontTypeLabel)
                    .addGroup(designTypeSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fontTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tteFontSizeLabel)
                        .addComponent(fontSizeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boldCheck)
                        .addComponent(italicCheck)))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backgroundColorsLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(colorNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addColorBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteColor))
                            .addComponent(otherColorsLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(otherBorderLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(colorBorderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(colorBorderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel19))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator7)
                            .addComponent(jSeparator4)
                            .addComponent(saveDesignBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(designTypeSubPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bgPlanLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(colorPlanCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(colorPlanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bgMotdLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(colorMotdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(colorMotdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bgTableLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(colorTableCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(colorTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addColorBtn)
                    .addComponent(deleteColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backgroundColorsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(colorMotdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bgMotdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bgPlanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(colorPlanCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(colorPlanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(colorMotdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(colorTableCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bgTableLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(11, 11, 11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(otherColorsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(otherBorderLabel)
                                .addComponent(colorBorderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(colorBorderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(colorTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(designTypeSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveDesignBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colorPlanComboItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_colorPlanComboItemStateChanged
    {//GEN-HEADEREND:event_colorPlanComboItemStateChanged
        //Application.addToQueue("colorPlanComboItemStateChanged");
    }//GEN-LAST:event_colorPlanComboItemStateChanged

    private void deleteColorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteColorActionPerformed
    {//GEN-HEADEREND:event_deleteColorActionPerformed
        //Application.addToQueue("deleteColorBtnActionPerformed");
    }//GEN-LAST:event_deleteColorActionPerformed

    private void addColorBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addColorBtnActionPerformed
    {//GEN-HEADEREND:event_addColorBtnActionPerformed
        //Application.addToQueue("addColorBtnActionPerformed");
    }//GEN-LAST:event_addColorBtnActionPerformed

    private void colorNameTxtFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_colorNameTxtFocusGained
    {//GEN-HEADEREND:event_colorNameTxtFocusGained
        //Application.addToQueue("colorNameTxtFocusGained");
    }//GEN-LAST:event_colorNameTxtFocusGained

    private void colorNameTxtFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_colorNameTxtFocusLost
    {//GEN-HEADEREND:event_colorNameTxtFocusLost
        //Application.addToQueue("colorNameTxtFocusLost");
    }//GEN-LAST:event_colorNameTxtFocusLost

    private void colorMotdComboItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_colorMotdComboItemStateChanged
    {//GEN-HEADEREND:event_colorMotdComboItemStateChanged
        //Application.addToQueue("colorMotdComboItemStateChanged");
    }//GEN-LAST:event_colorMotdComboItemStateChanged

    private void colorTableComboItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_colorTableComboItemStateChanged
    {//GEN-HEADEREND:event_colorTableComboItemStateChanged
        //Application.addToQueue("colorTableComboItemStateChanged");
    }//GEN-LAST:event_colorTableComboItemStateChanged

    private void colorBorderComboItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_colorBorderComboItemStateChanged
    {//GEN-HEADEREND:event_colorBorderComboItemStateChanged
        //Application.addToQueue("colorBorderComboItemStateChanged");
    }//GEN-LAST:event_colorBorderComboItemStateChanged

    private void saveDesignBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveDesignBtnActionPerformed
    {//GEN-HEADEREND:event_saveDesignBtnActionPerformed
        //Application.addToQueue("saveDesignBtnActionPerformed");
    }//GEN-LAST:event_saveDesignBtnActionPerformed

    private void deleteTypeBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteTypeBtnActionPerformed
    {//GEN-HEADEREND:event_deleteTypeBtnActionPerformed
        //Application.addToQueue("deleteTypeBtnActionPerformed");
    }//GEN-LAST:event_deleteTypeBtnActionPerformed

    private void addTypeBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addTypeBtnActionPerformed
    {//GEN-HEADEREND:event_addTypeBtnActionPerformed
        //Application.addToQueue("addTypeBtnActionPerformed");
    }//GEN-LAST:event_addTypeBtnActionPerformed

    private void typeToEditTxtFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_typeToEditTxtFocusGained
    {//GEN-HEADEREND:event_typeToEditTxtFocusGained
        //Application.addToQueue("typeToEditTxtFocusGained");
    }//GEN-LAST:event_typeToEditTxtFocusGained

    private void typeToEditTxtFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_typeToEditTxtFocusLost
    {//GEN-HEADEREND:event_typeToEditTxtFocusLost
        //Application.addToQueue("typeToEditTxtFocusLost");
    }//GEN-LAST:event_typeToEditTxtFocusLost

    private void typeToEditComboItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_typeToEditComboItemStateChanged
    {//GEN-HEADEREND:event_typeToEditComboItemStateChanged
        //Application.addToQueue("typeToEditComboItemStateChanged");
    }//GEN-LAST:event_typeToEditComboItemStateChanged

    private void fontColorComboItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_fontColorComboItemStateChanged
    {//GEN-HEADEREND:event_fontColorComboItemStateChanged
        //Application.addToQueue("fontColorComboItemStateChanged");
    }//GEN-LAST:event_fontColorComboItemStateChanged

    private void backgroundColorComboItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_backgroundColorComboItemStateChanged
    {//GEN-HEADEREND:event_backgroundColorComboItemStateChanged
        //Application.addToQueue("backgroundColorComboItemStateChanged");
    }//GEN-LAST:event_backgroundColorComboItemStateChanged

    private void fontTypeTxtMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_fontTypeTxtMouseExited
    {//GEN-HEADEREND:event_fontTypeTxtMouseExited
        //Application.addToQueue("fontTypeTxtActionPerformed");
    }//GEN-LAST:event_fontTypeTxtMouseExited

    private void fontSizeTxtMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_fontSizeTxtMouseExited
    {//GEN-HEADEREND:event_fontSizeTxtMouseExited
        //Application.addToQueue("fontSizeTxtActionPerformed");
    }//GEN-LAST:event_fontSizeTxtMouseExited

    private void boldCheckActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_boldCheckActionPerformed
    {//GEN-HEADEREND:event_boldCheckActionPerformed
        //Application.addToQueue("styleCheckActionPerformed");
    }//GEN-LAST:event_boldCheckActionPerformed

    private void italicCheckActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_italicCheckActionPerformed
    {//GEN-HEADEREND:event_italicCheckActionPerformed
        //Application.addToQueue("styleCheckActionPerformed");
    }//GEN-LAST:event_italicCheckActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addColorBtn;
    private javax.swing.JButton addTypeBtn;
    protected static javax.swing.JComboBox<String> backgroundColorCombo;
    protected static javax.swing.JPanel backgroundColorPanel;
    private javax.swing.JLabel backgroundColorsLabel;
    private javax.swing.JLabel bgMotdLabel;
    private javax.swing.JLabel bgPlanLabel;
    private javax.swing.JLabel bgTableLabel;
    protected static javax.swing.JCheckBox boldCheck;
    protected static javax.swing.JComboBox<String> colorBorderCombo;
    protected static javax.swing.JPanel colorBorderPanel;
    protected static javax.swing.JComboBox<String> colorMotdCombo;
    protected static javax.swing.JPanel colorMotdPanel;
    protected static javax.swing.JTextField colorNameTxt;
    protected static javax.swing.JComboBox<String> colorPlanCombo;
    protected static javax.swing.JPanel colorPlanPanel;
    protected static javax.swing.JComboBox<String> colorTableCombo;
    protected static javax.swing.JPanel colorTablePanel;
    private javax.swing.JButton deleteColor;
    private javax.swing.JButton deleteTypeBtn;
    private javax.swing.JPanel designTypeSubPanel;
    protected static javax.swing.JComboBox<String> fontColorCombo;
    protected static javax.swing.JPanel fontColorPanel;
    protected static javax.swing.JTextField fontSizeTxt;
    protected static javax.swing.JTextField fontTypeTxt;
    protected static javax.swing.JCheckBox italicCheck;
    protected static javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel otherBorderLabel;
    private javax.swing.JLabel otherColorsLabel;
    private javax.swing.JButton saveDesignBtn;
    protected static javax.swing.JLabel tteBgLabel;
    private javax.swing.JLabel tteFontColorLabel;
    private javax.swing.JLabel tteFontSizeLabel;
    private javax.swing.JLabel tteFontTypeLabel;
    protected static javax.swing.JComboBox<String> typeToEditCombo;
    private javax.swing.JLabel typeToEditLabel;
    protected static javax.swing.JTextField typeToEditTxt;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTabTitle()
    {
        return "Aussehen";
    }
}
